### ISSUE TITLE
Changing maxCarryWeight doesn't seem to work properly

### ISSUE THREAD

**Issue by lost-RD** [iso2t/Heavy-Inventories-Issues#3]
The bar in the gui knows that my max has increased but I still get slowed after 600 and stopped at 700.

On that point, a threshold config for when the player is slowed wouldn't hurt.

**Comment by iso2t** [comment]
interesting. ill look into it

**Comment by iso2t** [comment]
fixed. will be pushed in next update :)

**Comment by lost-RD** [comment]
I updated to 3.0.2 and the issue persists

**Comment by iso2t** [comment]
does it still happen in a new world? it has to due with NBTTags. im working on a fix for this issue.

**Comment by lost-RD** [comment]
I found the NBT in the player data and edited it which did not fix it. I also started a new world which did respect the config value. Also it seems like you’ve broke your localisation in this build and the chat command is gone?
